# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/design_1_axi_smc_3_0.xci
# IP: The module: 'design_1_axi_smc_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/bd_68d9.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_0/bd_68d9_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_1/bd_68d9_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_2/bd_68d9_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_3/bd_68d9_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_4/bd_68d9_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_5/bd_68d9_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_6/bd_68d9_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_7/bd_68d9_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_8/bd_68d9_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_9/bd_68d9_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_10/bd_68d9_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_11/bd_68d9_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_12/bd_68d9_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_1/bd_68d9_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_1/bd_68d9_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_5/bd_68d9_s00a2s_0_ooc.xdc

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_6/bd_68d9_sarn_0_ooc.xdc

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_7/bd_68d9_srn_0_ooc.xdc

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_8/bd_68d9_sawn_0_ooc.xdc

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_9/bd_68d9_swn_0_ooc.xdc

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_10/bd_68d9_sbn_0_ooc.xdc

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_11/bd_68d9_m00s2a_0_ooc.xdc

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_3_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/design_1_axi_smc_3_0.xci
# IP: The module: 'design_1_axi_smc_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/bd_68d9.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_0/bd_68d9_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_1/bd_68d9_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_2/bd_68d9_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_3/bd_68d9_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_4/bd_68d9_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_5/bd_68d9_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_6/bd_68d9_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_7/bd_68d9_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_8/bd_68d9_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_9/bd_68d9_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_10/bd_68d9_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_11/bd_68d9_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_12/bd_68d9_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_1/bd_68d9_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_1/bd_68d9_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_5/bd_68d9_s00a2s_0_ooc.xdc

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_6/bd_68d9_sarn_0_ooc.xdc

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_7/bd_68d9_srn_0_ooc.xdc

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_8/bd_68d9_sawn_0_ooc.xdc

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_9/bd_68d9_swn_0_ooc.xdc

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_10/bd_68d9_sbn_0_ooc.xdc

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/bd_0/ip/ip_11/bd_68d9_m00s2a_0_ooc.xdc

# XDC: /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
