-- Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2020.2 (lin64) Build 3064766 Wed Nov 18 09:12:47 MST 2020
-- Date        : Mon May  2 18:44:35 2022
-- Host        : ece-linlabsrv01.ece.gatech.edu running 64-bit Red Hat Enterprise Linux Server release 7.9 (Maipo)
-- Command     : write_vhdl -force -mode synth_stub
--               /nethome/sbn6/fpga/Lab3B/Lab3B_vivado/Lab3B_vivado.gen/sources_1/bd/design_1/ip/design_1_rayTriangleIntersect_0_0/design_1_rayTriangleIntersect_0_0_stub.vhdl
-- Design      : design_1_rayTriangleIntersect_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu3eg-sbva484-1-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity design_1_rayTriangleIntersect_0_0 is
  Port ( 
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 6 downto 0 );
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 6 downto 0 );
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_RREADY : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_dir_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_dir_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_dir_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_dir_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_dir_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_dir_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_dir_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_dir_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_dir_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_dir_AWVALID : out STD_LOGIC;
    m_axi_dir_AWREADY : in STD_LOGIC;
    m_axi_dir_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_dir_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_dir_WLAST : out STD_LOGIC;
    m_axi_dir_WVALID : out STD_LOGIC;
    m_axi_dir_WREADY : in STD_LOGIC;
    m_axi_dir_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_dir_BVALID : in STD_LOGIC;
    m_axi_dir_BREADY : out STD_LOGIC;
    m_axi_dir_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_dir_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_dir_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_dir_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_dir_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_dir_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_dir_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_dir_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_dir_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_dir_ARVALID : out STD_LOGIC;
    m_axi_dir_ARREADY : in STD_LOGIC;
    m_axi_dir_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_dir_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_dir_RLAST : in STD_LOGIC;
    m_axi_dir_RVALID : in STD_LOGIC;
    m_axi_dir_RREADY : out STD_LOGIC;
    m_axi_P1_DRAM_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_P1_DRAM_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_P1_DRAM_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_P1_DRAM_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P1_DRAM_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P1_DRAM_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P1_DRAM_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P1_DRAM_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_P1_DRAM_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P1_DRAM_AWVALID : out STD_LOGIC;
    m_axi_P1_DRAM_AWREADY : in STD_LOGIC;
    m_axi_P1_DRAM_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_P1_DRAM_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P1_DRAM_WLAST : out STD_LOGIC;
    m_axi_P1_DRAM_WVALID : out STD_LOGIC;
    m_axi_P1_DRAM_WREADY : in STD_LOGIC;
    m_axi_P1_DRAM_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P1_DRAM_BVALID : in STD_LOGIC;
    m_axi_P1_DRAM_BREADY : out STD_LOGIC;
    m_axi_P1_DRAM_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_P1_DRAM_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_P1_DRAM_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_P1_DRAM_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P1_DRAM_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P1_DRAM_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P1_DRAM_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P1_DRAM_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_P1_DRAM_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P1_DRAM_ARVALID : out STD_LOGIC;
    m_axi_P1_DRAM_ARREADY : in STD_LOGIC;
    m_axi_P1_DRAM_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_P1_DRAM_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P1_DRAM_RLAST : in STD_LOGIC;
    m_axi_P1_DRAM_RVALID : in STD_LOGIC;
    m_axi_P1_DRAM_RREADY : out STD_LOGIC;
    m_axi_P2_DRAM_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_P2_DRAM_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_P2_DRAM_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_P2_DRAM_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P2_DRAM_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P2_DRAM_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P2_DRAM_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P2_DRAM_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_P2_DRAM_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P2_DRAM_AWVALID : out STD_LOGIC;
    m_axi_P2_DRAM_AWREADY : in STD_LOGIC;
    m_axi_P2_DRAM_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_P2_DRAM_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P2_DRAM_WLAST : out STD_LOGIC;
    m_axi_P2_DRAM_WVALID : out STD_LOGIC;
    m_axi_P2_DRAM_WREADY : in STD_LOGIC;
    m_axi_P2_DRAM_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P2_DRAM_BVALID : in STD_LOGIC;
    m_axi_P2_DRAM_BREADY : out STD_LOGIC;
    m_axi_P2_DRAM_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_P2_DRAM_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_P2_DRAM_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_P2_DRAM_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P2_DRAM_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P2_DRAM_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P2_DRAM_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P2_DRAM_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_P2_DRAM_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P2_DRAM_ARVALID : out STD_LOGIC;
    m_axi_P2_DRAM_ARREADY : in STD_LOGIC;
    m_axi_P2_DRAM_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_P2_DRAM_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P2_DRAM_RLAST : in STD_LOGIC;
    m_axi_P2_DRAM_RVALID : in STD_LOGIC;
    m_axi_P2_DRAM_RREADY : out STD_LOGIC;
    m_axi_P3_DRAM_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_P3_DRAM_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_P3_DRAM_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_P3_DRAM_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P3_DRAM_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P3_DRAM_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P3_DRAM_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P3_DRAM_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_P3_DRAM_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P3_DRAM_AWVALID : out STD_LOGIC;
    m_axi_P3_DRAM_AWREADY : in STD_LOGIC;
    m_axi_P3_DRAM_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_P3_DRAM_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P3_DRAM_WLAST : out STD_LOGIC;
    m_axi_P3_DRAM_WVALID : out STD_LOGIC;
    m_axi_P3_DRAM_WREADY : in STD_LOGIC;
    m_axi_P3_DRAM_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P3_DRAM_BVALID : in STD_LOGIC;
    m_axi_P3_DRAM_BREADY : out STD_LOGIC;
    m_axi_P3_DRAM_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_P3_DRAM_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_P3_DRAM_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_P3_DRAM_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P3_DRAM_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P3_DRAM_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P3_DRAM_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P3_DRAM_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_P3_DRAM_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_P3_DRAM_ARVALID : out STD_LOGIC;
    m_axi_P3_DRAM_ARREADY : in STD_LOGIC;
    m_axi_P3_DRAM_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_P3_DRAM_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_P3_DRAM_RLAST : in STD_LOGIC;
    m_axi_P3_DRAM_RVALID : in STD_LOGIC;
    m_axi_P3_DRAM_RREADY : out STD_LOGIC;
    m_axi_intersectIndex_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_intersectIndex_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_intersectIndex_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_intersectIndex_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_intersectIndex_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_intersectIndex_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_intersectIndex_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_intersectIndex_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_intersectIndex_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_intersectIndex_AWVALID : out STD_LOGIC;
    m_axi_intersectIndex_AWREADY : in STD_LOGIC;
    m_axi_intersectIndex_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_intersectIndex_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_intersectIndex_WLAST : out STD_LOGIC;
    m_axi_intersectIndex_WVALID : out STD_LOGIC;
    m_axi_intersectIndex_WREADY : in STD_LOGIC;
    m_axi_intersectIndex_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_intersectIndex_BVALID : in STD_LOGIC;
    m_axi_intersectIndex_BREADY : out STD_LOGIC;
    m_axi_intersectIndex_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_intersectIndex_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_intersectIndex_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_intersectIndex_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_intersectIndex_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_intersectIndex_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_intersectIndex_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_intersectIndex_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_intersectIndex_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_intersectIndex_ARVALID : out STD_LOGIC;
    m_axi_intersectIndex_ARREADY : in STD_LOGIC;
    m_axi_intersectIndex_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_intersectIndex_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_intersectIndex_RLAST : in STD_LOGIC;
    m_axi_intersectIndex_RVALID : in STD_LOGIC;
    m_axi_intersectIndex_RREADY : out STD_LOGIC
  );

end design_1_rayTriangleIntersect_0_0;

architecture stub of design_1_rayTriangleIntersect_0_0 is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "s_axi_control_AWADDR[6:0],s_axi_control_AWVALID,s_axi_control_AWREADY,s_axi_control_WDATA[31:0],s_axi_control_WSTRB[3:0],s_axi_control_WVALID,s_axi_control_WREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_BREADY,s_axi_control_ARADDR[6:0],s_axi_control_ARVALID,s_axi_control_ARREADY,s_axi_control_RDATA[31:0],s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_RREADY,ap_clk,ap_rst_n,interrupt,m_axi_dir_AWADDR[63:0],m_axi_dir_AWLEN[7:0],m_axi_dir_AWSIZE[2:0],m_axi_dir_AWBURST[1:0],m_axi_dir_AWLOCK[1:0],m_axi_dir_AWREGION[3:0],m_axi_dir_AWCACHE[3:0],m_axi_dir_AWPROT[2:0],m_axi_dir_AWQOS[3:0],m_axi_dir_AWVALID,m_axi_dir_AWREADY,m_axi_dir_WDATA[31:0],m_axi_dir_WSTRB[3:0],m_axi_dir_WLAST,m_axi_dir_WVALID,m_axi_dir_WREADY,m_axi_dir_BRESP[1:0],m_axi_dir_BVALID,m_axi_dir_BREADY,m_axi_dir_ARADDR[63:0],m_axi_dir_ARLEN[7:0],m_axi_dir_ARSIZE[2:0],m_axi_dir_ARBURST[1:0],m_axi_dir_ARLOCK[1:0],m_axi_dir_ARREGION[3:0],m_axi_dir_ARCACHE[3:0],m_axi_dir_ARPROT[2:0],m_axi_dir_ARQOS[3:0],m_axi_dir_ARVALID,m_axi_dir_ARREADY,m_axi_dir_RDATA[31:0],m_axi_dir_RRESP[1:0],m_axi_dir_RLAST,m_axi_dir_RVALID,m_axi_dir_RREADY,m_axi_P1_DRAM_AWADDR[63:0],m_axi_P1_DRAM_AWLEN[7:0],m_axi_P1_DRAM_AWSIZE[2:0],m_axi_P1_DRAM_AWBURST[1:0],m_axi_P1_DRAM_AWLOCK[1:0],m_axi_P1_DRAM_AWREGION[3:0],m_axi_P1_DRAM_AWCACHE[3:0],m_axi_P1_DRAM_AWPROT[2:0],m_axi_P1_DRAM_AWQOS[3:0],m_axi_P1_DRAM_AWVALID,m_axi_P1_DRAM_AWREADY,m_axi_P1_DRAM_WDATA[31:0],m_axi_P1_DRAM_WSTRB[3:0],m_axi_P1_DRAM_WLAST,m_axi_P1_DRAM_WVALID,m_axi_P1_DRAM_WREADY,m_axi_P1_DRAM_BRESP[1:0],m_axi_P1_DRAM_BVALID,m_axi_P1_DRAM_BREADY,m_axi_P1_DRAM_ARADDR[63:0],m_axi_P1_DRAM_ARLEN[7:0],m_axi_P1_DRAM_ARSIZE[2:0],m_axi_P1_DRAM_ARBURST[1:0],m_axi_P1_DRAM_ARLOCK[1:0],m_axi_P1_DRAM_ARREGION[3:0],m_axi_P1_DRAM_ARCACHE[3:0],m_axi_P1_DRAM_ARPROT[2:0],m_axi_P1_DRAM_ARQOS[3:0],m_axi_P1_DRAM_ARVALID,m_axi_P1_DRAM_ARREADY,m_axi_P1_DRAM_RDATA[31:0],m_axi_P1_DRAM_RRESP[1:0],m_axi_P1_DRAM_RLAST,m_axi_P1_DRAM_RVALID,m_axi_P1_DRAM_RREADY,m_axi_P2_DRAM_AWADDR[63:0],m_axi_P2_DRAM_AWLEN[7:0],m_axi_P2_DRAM_AWSIZE[2:0],m_axi_P2_DRAM_AWBURST[1:0],m_axi_P2_DRAM_AWLOCK[1:0],m_axi_P2_DRAM_AWREGION[3:0],m_axi_P2_DRAM_AWCACHE[3:0],m_axi_P2_DRAM_AWPROT[2:0],m_axi_P2_DRAM_AWQOS[3:0],m_axi_P2_DRAM_AWVALID,m_axi_P2_DRAM_AWREADY,m_axi_P2_DRAM_WDATA[31:0],m_axi_P2_DRAM_WSTRB[3:0],m_axi_P2_DRAM_WLAST,m_axi_P2_DRAM_WVALID,m_axi_P2_DRAM_WREADY,m_axi_P2_DRAM_BRESP[1:0],m_axi_P2_DRAM_BVALID,m_axi_P2_DRAM_BREADY,m_axi_P2_DRAM_ARADDR[63:0],m_axi_P2_DRAM_ARLEN[7:0],m_axi_P2_DRAM_ARSIZE[2:0],m_axi_P2_DRAM_ARBURST[1:0],m_axi_P2_DRAM_ARLOCK[1:0],m_axi_P2_DRAM_ARREGION[3:0],m_axi_P2_DRAM_ARCACHE[3:0],m_axi_P2_DRAM_ARPROT[2:0],m_axi_P2_DRAM_ARQOS[3:0],m_axi_P2_DRAM_ARVALID,m_axi_P2_DRAM_ARREADY,m_axi_P2_DRAM_RDATA[31:0],m_axi_P2_DRAM_RRESP[1:0],m_axi_P2_DRAM_RLAST,m_axi_P2_DRAM_RVALID,m_axi_P2_DRAM_RREADY,m_axi_P3_DRAM_AWADDR[63:0],m_axi_P3_DRAM_AWLEN[7:0],m_axi_P3_DRAM_AWSIZE[2:0],m_axi_P3_DRAM_AWBURST[1:0],m_axi_P3_DRAM_AWLOCK[1:0],m_axi_P3_DRAM_AWREGION[3:0],m_axi_P3_DRAM_AWCACHE[3:0],m_axi_P3_DRAM_AWPROT[2:0],m_axi_P3_DRAM_AWQOS[3:0],m_axi_P3_DRAM_AWVALID,m_axi_P3_DRAM_AWREADY,m_axi_P3_DRAM_WDATA[31:0],m_axi_P3_DRAM_WSTRB[3:0],m_axi_P3_DRAM_WLAST,m_axi_P3_DRAM_WVALID,m_axi_P3_DRAM_WREADY,m_axi_P3_DRAM_BRESP[1:0],m_axi_P3_DRAM_BVALID,m_axi_P3_DRAM_BREADY,m_axi_P3_DRAM_ARADDR[63:0],m_axi_P3_DRAM_ARLEN[7:0],m_axi_P3_DRAM_ARSIZE[2:0],m_axi_P3_DRAM_ARBURST[1:0],m_axi_P3_DRAM_ARLOCK[1:0],m_axi_P3_DRAM_ARREGION[3:0],m_axi_P3_DRAM_ARCACHE[3:0],m_axi_P3_DRAM_ARPROT[2:0],m_axi_P3_DRAM_ARQOS[3:0],m_axi_P3_DRAM_ARVALID,m_axi_P3_DRAM_ARREADY,m_axi_P3_DRAM_RDATA[31:0],m_axi_P3_DRAM_RRESP[1:0],m_axi_P3_DRAM_RLAST,m_axi_P3_DRAM_RVALID,m_axi_P3_DRAM_RREADY,m_axi_intersectIndex_AWADDR[63:0],m_axi_intersectIndex_AWLEN[7:0],m_axi_intersectIndex_AWSIZE[2:0],m_axi_intersectIndex_AWBURST[1:0],m_axi_intersectIndex_AWLOCK[1:0],m_axi_intersectIndex_AWREGION[3:0],m_axi_intersectIndex_AWCACHE[3:0],m_axi_intersectIndex_AWPROT[2:0],m_axi_intersectIndex_AWQOS[3:0],m_axi_intersectIndex_AWVALID,m_axi_intersectIndex_AWREADY,m_axi_intersectIndex_WDATA[31:0],m_axi_intersectIndex_WSTRB[3:0],m_axi_intersectIndex_WLAST,m_axi_intersectIndex_WVALID,m_axi_intersectIndex_WREADY,m_axi_intersectIndex_BRESP[1:0],m_axi_intersectIndex_BVALID,m_axi_intersectIndex_BREADY,m_axi_intersectIndex_ARADDR[63:0],m_axi_intersectIndex_ARLEN[7:0],m_axi_intersectIndex_ARSIZE[2:0],m_axi_intersectIndex_ARBURST[1:0],m_axi_intersectIndex_ARLOCK[1:0],m_axi_intersectIndex_ARREGION[3:0],m_axi_intersectIndex_ARCACHE[3:0],m_axi_intersectIndex_ARPROT[2:0],m_axi_intersectIndex_ARQOS[3:0],m_axi_intersectIndex_ARVALID,m_axi_intersectIndex_ARREADY,m_axi_intersectIndex_RDATA[31:0],m_axi_intersectIndex_RRESP[1:0],m_axi_intersectIndex_RLAST,m_axi_intersectIndex_RVALID,m_axi_intersectIndex_RREADY";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "rayTriangleIntersect,Vivado 2020.2";
begin
end;
